-- Generated by `npm run roster` on 2026-09-30 14:46.
-- 14 students, 6 staff. If that does not match what you
-- expect, you are looking at an old copy -- reopen supabase/roster.sql.
--
-- Run this in the Supabase SQL editor.
--
-- Idempotent: running it twice changes nothing. Adding a late student is
-- the same command again with the full list, including the new code.
--
-- The SAME roster must be seeded in VibeBuilder's project, or the week
-- stops joining on one key and a student is two people in the data.

insert into students (username, role) values
  ('SFR99', 'student'),
  ('CGU11', 'student'),
  ('IGW93', 'student'),
  ('ZJA69', 'student'),
  ('AWC18', 'student'),
  ('GRB32', 'student'),
  ('TVK34', 'student'),
  ('FSL32', 'student'),
  ('LCY62', 'student'),
  ('IEZ40', 'student'),
  ('YMR58', 'student'),
  ('KAN66', 'student'),
  ('CBE47', 'student'),
  ('QCT22', 'student'),
  ('SAM12', 'instructor'),
  ('SAM14', 'instructor'),
  ('SAM16', 'instructor'),
  ('KSS11', 'instructor'),
  ('KSS03', 'instructor'),
  ('KSS18', 'instructor')
on conflict (username) do update set role = excluded.role;

-- Should print 14 student and 7 instructor (the staff cards plus KSS17).
select role, count(*) from students group by role order by role;
