#!/usr/bin/env node
/**
 * Put the class roster where the app needs it. Two places, one command.
 *
 *   npm run roster -- ABC12 DEF34 GHI56 ...
 *   npm run roster -- --file roster.txt        (one code per line)
 *   npm run roster -- --check                  (report, change nothing)
 *
 * THE CODES GO IN TWO PLACES AND THEY MUST MATCH.
 *
 *   1. supabase/roster.sql -> run in the SQL editor. This seeds `students`,
 *      which is what check_roster() answers from. A code that is not there
 *      is refused at sign-in as a typo.
 *
 *   2. ROSTER in src/roster.js -> shipped in the bundle. This is the
 *      ORDER the codes are dealt in, and it is what makes AlwaysNever's
 *      rule assignment balanced instead of lumpy. With it empty, assignment
 *      falls back to hashing the code: a simulated class of fourteen came
 *      out 6/5/3/3/5/6 across the six arrangements, leaving one rule barely
 *      seen in the supported condition. Dealt from this list it is
 *      5/5/4/5/5/4.
 *
 * A code seeded in one place and missing from the other fails QUIETLY --
 * the student signs in fine and is assigned by hash, or is refused at
 * sign-in on a morning nobody can debug it. Writing both from one source
 * is the point of this script.
 *
 * NO NAMES. This never asks for them and they never enter the repo. The
 * name a student types at sign-in goes on their `sessions` row and nowhere
 * else; the paper roster that maps a name to a code stays with you.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const SQL_OUT = join(ROOT, "supabase", "roster.sql");
const ROSTER_JS = join(ROOT, "src", "roster.js");

const CODE_RE = /^[A-Z]{3}[0-9]{2}$/;          // ABC12 — matches normalizeCode
const INSTRUCTOR = "KSS17";

const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const fileAt = args.indexOf("--file");

let raw = [];
if (fileAt >= 0) {
  const p = args[fileAt + 1];
  if (!p || !existsSync(p)) { console.error("No such file: " + p); process.exit(2); }
  raw = readFileSync(p, "utf8").split(/[\s,]+/);
} else {
  raw = args.filter((a) => !a.startsWith("--"));
}

/* ---- read what is already there, so --check can say something useful --- */
const js = readFileSync(ROSTER_JS, "utf8");
const current = (js.match(/export const ROSTER = \[([\s\S]*?)\];/) || [, ""])[1]
  .split(/[",\s]+/).filter(Boolean);

if (checkOnly || !raw.length) {
  console.log(`src/roster.js holds ${current.length} code(s)` + (current.length ? ":" : "."));
  if (current.length) console.log("  " + current.join(" "));
  console.log(existsSync(SQL_OUT)
    ? `supabase/roster.sql exists — run it in the SQL editor if you have not.`
    : `supabase/roster.sql has not been written yet.`);
  if (!raw.length && !checkOnly) {
    console.log("\nTo set the roster:  npm run roster -- ABC12 DEF34 ...");
    console.log("                    npm run roster -- --file roster.txt");
  }
  process.exit(0);
}

/* ---- validate, loudly, before anything is written --------------------- */
const codes = [];
const problems = [];
for (const r of raw) {
  const c = r.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!c) continue;
  if (c === INSTRUCTOR) { problems.push(`${r}: that is the instructor key, which is seeded already`); continue; }
  if (!CODE_RE.test(c)) { problems.push(`${r}: not code-shaped (want three letters then two digits, like ABC12)`); continue; }
  if (codes.includes(c)) { problems.push(`${c}: listed twice`); continue; }
  codes.push(c);
}

if (problems.length) {
  console.error("Nothing was written. Fix these first:\n");
  for (const p of problems) console.error("  " + p);
  process.exit(1);
}
if (!codes.length) { console.error("No usable codes."); process.exit(1); }

/* ---- 1. the SQL ------------------------------------------------------- */
const sql = [
  "-- Generated by `npm run roster`. Run this in the Supabase SQL editor.",
  "--",
  "-- Idempotent: running it twice changes nothing. Adding a late student is",
  "-- the same command again with the full list, including the new code.",
  "--",
  "-- The SAME roster must be seeded in VibeBuilder's project, or the week",
  "-- stops joining on one key and a student is two people in the data.",
  "",
  "insert into students (username, role) values",
  codes.map((c) => `  ('${c}', 'student')`).join(",\n") + "",
  "on conflict (username) do update set role = excluded.role;",
  "",
  "-- Sanity check: should print " + codes.length + ".",
  "select count(*) from students where role = 'student';",
  "",
].join("\n");
writeFileSync(SQL_OUT, sql);

/* ---- 2. the ordered list in the bundle -------------------------------- */
const block = "export const ROSTER = [\n"
  + codes.map((c) => `  "${c}",`).join("\n")
  + "\n];";
const next = js.replace(/export const ROSTER = \[[\s\S]*?\];/, block);
if (next === js) { console.error("Could not find ROSTER in src/roster.js — not written."); process.exit(1); }
writeFileSync(ROSTER_JS, next);

/* ---- what happens next ------------------------------------------------ */
console.log(`${codes.length} codes: ${codes.join(" ")}\n`);
console.log("  wrote supabase/roster.sql   -> run it in the Supabase SQL editor");
console.log("  wrote src/roster.js ROSTER  -> commit and deploy\n");
console.log("Still to do by hand:");
console.log("  - set DEMO = false in src/demo.js, or none of this is used");
console.log("  - run the same roster.sql in VibeBuilder's Supabase project");
