/**
 * The two passwords, as salted SHA-256 digests.
 *
 * Generated by `npm run passwords`. Do not hand-edit — set them with
 *
 *   npm run passwords -- entry=<word> admin=<word>
 *
 * `entry` opens CT Week and is read out to the class. `admin` opens the
 * page that decides which tiles are open and is yours alone. They are
 * checked to be different words, because telling the class the admin word
 * by accident hands them the whole week.
 *
 * BE HONEST ABOUT WHAT THIS IS. The digests ship in the client bundle, and a
 * dictionary word behind a single SHA-256 is minutes of work for an adult
 * with a wordlist. This stops a student who opens devtools out of curiosity;
 * it does not stop anyone who is trying. The reason it is hashed rather than
 * written in plain text is so the words are not sitting in a public GitHub
 * repo for anyone to read at a glance.
 *
 * What `entry` is actually for: keeping the URL from being the whole key, so
 * a link forwarded to a sibling does not put a stranger in the study data.
 * What `admin` is for: making sure the person changing what the class can
 * see is you. For that they are enough. Do not describe either to the IRB as
 * access control.
 */
export const PASSWORD_SALT = "ctx3";
export const PASSWORDS = {
  entry: "20b22b9ef306be2ac3016ae9744f64dd9dc5d87746e86abec6afb6850f72fcba",
  admin: "b6a46c938ba2f50f5a1cffc9f563d4e66e8d2ce060f3060cc6cb11dc6cb19536",
};
