/**
 * Activity passwords, as salted SHA-256 digests.
 *
 * Generated by `npm run passwords`. Do not hand-edit — set them with
 *
 *   npm run passwords -- ftr=<word> pg=<word> w4w=<word>
 *
 * BE HONEST ABOUT WHAT THIS IS. The digests ship in the client bundle, and a
 * dictionary word behind a single SHA-256 is minutes of work for an adult
 * with a wordlist. This stops a student who opens devtools out of curiosity;
 * it does not stop anyone who is trying. The reason it is hashed rather than
 * written in plain text is so the words are not sitting in a public GitHub
 * repo for anyone to read at a glance.
 *
 * What the password is actually for: making the facilitator the one who
 * decides when the room starts an activity, and keeping a class off Thursday's
 * tool on Tuesday. For that it is enough. Do not describe it to the IRB as
 * access control.
 *
 * A tool missing from this object has no password and opens straight away.
 */
export const PASSWORD_SALT = "ctx3";
export const PASSWORDS = {
  ftr: "82d3a72a20e916aef8649f366874d8067c98e694f70df18d88138343af6e42c5",
  pg: "697c19741fccc4315ab35d2e3817ca1ee07e210a2307132889f1803914799327",
  w4w: "1eea6991b2399d492d008b9029416aaaa195585901cbbb6b7010362627c3b3bd",
};
