/**
 * Activity passwords, as salted SHA-256 digests.
 *
 * Generated by `npm run passwords`. Do not hand-edit — set them with
 *
 *   npm run passwords -- ftr=<word> pg=<word> w4w=<word>
 *
 * BE HONEST ABOUT WHAT THIS IS. The digests ship in the client bundle, and a
 * dictionary word behind a single SHA-256 is minutes of work for an adult
 * with a wordlist. This stops a student who opens devtools out of curiosity;
 * it does not stop anyone who is trying. The reason it is hashed rather than
 * written in plain text is so the words are not sitting in a public GitHub
 * repo for anyone to read at a glance.
 *
 * What the password is actually for: making the facilitator the one who
 * decides when the room starts an activity, and keeping a class off Thursday's
 * tool on Tuesday. For that it is enough. Do not describe it to the IRB as
 * access control.
 *
 * A tool missing from this object has no password and opens straight away.
 */
export const PASSWORD_SALT = "ctx3";
export const PASSWORDS = {
  ftr: "dd03896c0a188dd8394eb68e12bd04c2cd5125cbfee2eea1a0e38d9dcaf911ef",
  pg: "780f2ba9b0c5363a5d0749ce81d7907ba52a931e77ef8d9909ec10c1332ea0de",
  w4w: "35a87014437e730c9123dcc80f5c2638025b0f2daad97120615fea6c650c53a9",
};
